const fs = require('fs')
const data = [
    {
        id: 1,
        type: 'blast',
        date: new Date(2021,4, 6),
        name: 'May Classes with availability',
        opens: 12.2,
        clicks: 1.1,
        sales: [295, 165, 75],
        free: 0,
        unsubs: 4,
    },
    {
        id: 2,
        type: 'blast',
        date: new Date(2021,4, 5),
        name: 'TGS Weekly Classes Wednesday Blast',
        opens: 11.6,
        clicks: 0.5,
        sales: [295,150,150],
        free: 2,
        unsubs: 3,
    },
    {
        id: 3,
        type: 'ind',
        date: new Date(2021,4,4),
        name: 'Phantom of the Opera Resident Director',
        opens: 12,
        clicks: 0.1,
        sales: [295],
        free: 0,
        unsubs: 4
    },
    {
        id: 4,
        type: 'blast',
        date: new Date(2021,4,3),
        name: 'TGS Weekly Classes starting 5/3',
        opens: 13.2,
        clicks: 0.8,
        sales: [365,125,345,295],
        free: 4,
        unsubs: 5,
    },
    {
        id: 5,
        type: 'blast',
        date: new Date(2021,4,3),
        name: 'Tonight Acting for the Camera Level 1 Goals...',
        opens: 18.2,
        clicks: 0.2,
        sales: [365,335,335,335],
        free: 0,
        unsubs: 4,
    },
    {
        id: 6,
        type: 'ind',
        date: new Date(2021,3,30),
        name: 'Free Seminar',
        opens: 13.9,
        clicks: 1.0,
        sales: [125,100],
        free: 74
    },
    {
        id: 7,
        type: 'ind',
        date: new Date(2021,3,30),
        name: 'Regional Theatre Series',
        opens: 14.5,
        clicks: 0.1,
        sales: [325],
        free: 0,
    },
    {
        id: 8,
        type: 'ind',
        name: 'Dance With Broadway',
        date: new Date(2021,3,29),
        opens: 12.4,
        clicks: 0.2,
        sales: [295],
        free: 1
    },
    {
        id: 9,
        type: 'ind',
        name: 'TV/Film Agent',
        date: new Date(2021,3,29),
        opens: 12.4,
        clicks: 0.3,
        sales: [301,301,301,301,301],
        free: 0,
    },
    {
        id: 10,
        type: 'ind',
        name: 'Michael Greif Master Class (free)',
        date: new Date(2021,3,26),
        opens: 14,
        clicks: 0.2,
        sales: [],
        free: 4
    },
    {
        id: 11,
        type: 'ind',
        name: 'Fosse Dance Workshop',
        date: new Date(2021,3,28),
        opens: 12.2,
        clicks: 0.2,
        sales: [150],
        free: 0,
    },
    {
        id: 12,
        type: 'ind',
        name: 'Dear Evan Hansen',
        date: new Date(2021,3,28),
        opens: 14.6,
        clicks: 0.2,
        sales: [295,295,295],
        free: 0,
    },
    {
        id: 13,
        type: 'ind',
        name: 'Duncan Stewart',
        date: new Date(2021,3,27),
        opens: 24.5,
        clicks: 0.2,
        sales: [350,350,350,350],
        free: 2
    },
    {
        id: 14,
        type: 'ind',
        name: 'Phandom of the Opera',
        date: new Date(2021,3,27),
        opens: 13.2,
        clicks: 0.2,
        sales: [295,295,295,295,295],
        free: 0,
    },
    {
        id: 15,
        type: 'ind',
        name: 'Regional Push',
        date: new Date(2021,4,7),
        opens: 13.6,
        clicks: 0.2,
        sales: [],
        free: 0,
        unsubs: 6
    },
    {
        id: 16,
        type: 'ind',
        name: '2 Spots left - MT CDW',
        date: new Date(2021,4,9),
        opens: 10.4,
        clicks: 0.1,
        sales: [],
        free: 0,
        unsubs: 3,
    },
    {
        id: 16,
        type: 'ind',
        name: 'Musical Theatre Casting Director Workshop MAY',
        date: new Date(2021,3,27),
        opens: 14.8,
        clicks: 0.3,
        sales: [3640],
        free: 0,
        unsubs: 4,
    },
    {
        id: 17,
        type: 'ind',
        name: 'COMMERCIAL AGENT SHOWCASE',
        date: new Date(2021,3,23),
        opens: 11.5,
        clicks: 0.1,
        sales: [490],
        free: 0,
    },
    {
        id: 18,
        type: 'ind',
        name: 'Blain Johnston TV/FILM Casting Gamechanger',
        date: new Date(2021,3,23),
        opens: 21.2,
        clicks: 0.6,
        sales: [1150],
        free: 0,
    },
    {
        id: 19,
        type: 'ind',
        name: 'Voice Over Level 1',
        date: new Date(2021,3,23),
        opens: 11.4,
        clicks: 0.1,
        sales: [670],
        free: 0,
    },
    {
        id: 20,
        type: 'ind',
        name: 'Harry Potter Push',
        date: new Date(2021,3,22),
        opens: 15.2,
        clicks: 0.2,
        sales: [125],
        free: 0,
    },
    {
        id: 21,
        type: 'ind',
        name: 'MICHAEL GRIEF MASTER CLASS',
        date: new Date(2021,3,21),
        opens: 13.4,
        clicks: 0.2,
        sales: [295],
        free: 0,
    },
    {
        id: 22,
        type: 'ind',
        name: 'Voice Over Animation Serries',
        date: new Date(2021,3,20),
        opens: 11.7,
        clicks: 0.2,
        sales: [275],
        free: 0,
    },
    {
        id: 23,
        type: 'ind',
        name: 'DEAR EVEN HANSEN Resident director series ',
        date: new Date(2021,3,22),
        opens: 11.9,
        clicks: 0.1,
        sales: [],
        free: 0,
    },
    {
        id: 24,
        type: 'ind',
        name: 'DEAR EVEN HANSEN Resident director series',
        date: new Date(2021,3,22),
        opens: 11.9,
        clicks: 0.1,
        sales: [],
        free: 0,
    },
    {
        id: 25,
        type: 'ind',
        name: 'Acting for the Camera Level 1',
        date: new Date(2021,3,19),
        opens: 22.8,
        clicks: 0.2,
        sales: [200],
        free: 0,
    },
    {
        id: 26,
        type: 'ind',
        name: 'TGS WEEKLY Classes starting 4/18',
        date: new Date(2021,3,19),
        opens: 12.8,
        clicks: 0.8,
        sales: [200],
        free: 0,
    },
    {
        id: 27,
        type: 'ind',
        name: 'Royal Caribean Cruise Line',
        date: new Date(2021,3,16),
        opens: 13.6,
        clicks: 0.1,
        sales: [70],
        free: 0,
    },
    {
        id: 28,
        type: 'ind',
        name: 'Acting for Cam / Voice Over Level 1 Section 2 PUSH',
        date: new Date(2021,3,16),
        opens: 11.9,
        clicks: 0.2,
        sales: [],
        free: 0,
    },
    {
        id: 29,
        type: 'ind',
        name: 'TV/Film Pilot Agent Series',
        date: new Date(2021,3,15),
        opens: 12.7,
        clicks: 0.2,
        sales: [2190],
        free: 0,
    },
    {
        id: 30,
        type: 'ind',
        name: 'WICKED Resident Director Series',
        date: new Date(2021,3,15),
        opens: 12.7,
        clicks: 0.2,
        sales: [1755],
        free: 0,
    },
    {
        id: 31,
        type: 'ind',
        name: 'Harry Potter and the Cursed Child',
        date: new Date(2021,3,14),
        opens: 13.6,
        clicks: 0.2,
        sales: [940],
        free: 0,
    },
    {
        id: 32,
        type: 'ind',
        name: 'Non-Union National Tour Series',
        date: new Date(2021,3,14),
        opens: 15.7,
        clicks: 0.2,
        sales: [170],
        free: 0,
    },
    {
        id: 33,
        type: 'ind',
        name: 'DES MCANUFF Master Class',
        date: new Date(2021,3,12),
        opens: 13.3,
        clicks: 0.1,
        sales: [],
        free: 0,
    },
    {
        id: 34,
        type: 'ind',
        name: 'NORWEGIAN CRUISE LINE',
        date: new Date(2021,3,12),
        opens: 16.4,
        clicks: 0.3,
        sales: [350],
        free: 0,
    },
    {
        id: 36,
        type: 'blast',
        name: 'TGS Upcoming Available Classes',
        date: new Date(2021,3,12),
        opens: 13.5,
        clicks: 0.7,
        sales: [295,295, 170,335],
        free: 3,
    },
    {
        id: 37,
        type: 'ind',
        name: 'Maria Torres Seminar Push',
        date: new Date(2021,3,9),
        opens: 13.0,
        clicks: 0.2,
        sales: [],
        free: 0,
    },
    {
        id: 38,
        type: 'ind',
        name: 'TGS MASTER CLASS SERIES',
        date: new Date(2021,3,7),
        opens: 13.5,
        clicks: 0.3,
        sales: [],
        free: 0,
    },
]
fs.writeFileSync('email.json', JSON.stringify(data));